Feature/issue 007 data module
YAPP-Github/20th-Android-Team-1-FE pull request #23
Opened 2022-05-19 13:02 UTC by hoyahozz

## ISSUE
- resolved #7 

<br>

## 작업 내용
- data 모듈 생성
- 생성된 app 모듈에 의존성 추가
- 샘플 클래스 추가

<br>

## 실행 화면

| Screen Shot | Screen Shot |
| ----------- | ----------- |
|             |             |

<br>

## Check List
- [X] PR 제목은 `[TICKET-{N}] PR 제목`으로 작성
- [ ] CI/CD 통과 여부
- [] 1명 이상의 Approve 확인 후 Merge
- [X] 관련 이슈 연결

2022-05-19 15:33 UTC, KwonDae requested changes
@hoyahozz 
고생하셔써요 정호님
몇군데만 수정하면 좋을듯
그리고 글라이드, Okhttp 등 통신 라이브러리도 작업해서 넣어주세요

2022-05-19 15:33 UTC, KwonDae commented on data/src/main/java/co/kr/yapp/growth/data/repository/RepositoryImpl.kt
> +package co.kr.yapp.growth.data.repository
패키지명 수정 ㅠ

2022-05-19 15:56 UTC, KwonDae commented on data/src/main/java/co/kr/yapp/growth/data/repository/RepositoryImpl.kt
> +package co.kr.yapp.growth.data.repository
LGTM 👍

2022-05-20 10:17 UTC, hoyahozz commented on data/build.gradle.kts
> +dependencies {
오 근데 그 글라이드 라이브러리가 프레젠테이션이 아니라 데이터 모듈에 들어가나용 ??

2022-05-20 10:25 UTC, jihee-dev commented on data/build.gradle.kts
> +dependencies {
근데 저희 글라이드 사용하나용? 컴포즈에서 글라이드가 공식 지원이 안 되어서 컴포즈에서는 보통 Coil을 사용하는 것으로 알고 있어서 여쭤봅니다! 아니면 혹쉬 글라이드도 이제 지원이 되는 것으로 업데이트 된 것인지..??

2022-05-20 10:26 UTC, jihee-dev commented on data/build.gradle.kts
> +dependencies {
Coil(혹은 글라이드, ...) 요 아이들은 프레젠테이션 모듈 쪽에 의존성 추가해야 할 것 같아요!

2022-05-20 10:30 UTC, jihee-dev requested changes
리뷰 드린 부분만 사소하게.. 수정해 주시면 감사하겠습니다!! 👍

2022-05-20 10:30 UTC, jihee-dev commented on buildSrc/src/main/java/Modules.kt
> +    const val DATA       = ":data"
요고 아예 다 자동 정렬으로 하거나, 탭으로 구분하려면 위쪽 간격과 맞춰 주세요..!

2022-05-20 10:30 UTC, jihee-dev commented on data/src/androidTest/java/com/yapp/growth/data/ExampleInstrumentedTest.kt
> +        assertEquals("co.kr.yapp.growth.data.test", appContext.packageName)
이거 패키지명 수정하면 자동으로 수정되는 건지는 모르겠는데.. 요 아이도 같이 수정되어야 할 것 같아요!
Test 코드를 적극적으로 사용하게 될 것 같진 않지만.. 먼가 불편해서... ㅎㅎㅎ...

2022-05-20 10:30 UTC, jihee-dev commented on domain/src/main/java/com/yapp/growth/domain/entity/entity.kt
> +class entity {
클래스명 첫 글자는 대문자.. 부탁드려용!

2022-05-20 10:30 UTC, jihee-dev commented on domain/src/main/java/com/yapp/growth/domain/repository/repository.kt
> +interface repository {
이 친구도..! 대문자..!

2022-05-20 10:30 UTC, jihee-dev commented on domain/src/main/java/com/yapp/growth/domain/usecase/useCase.kt
> +class useCase {
요 아이까지! 대문자로 수정 부탁드립니다~~

2022-05-20 10:47 UTC, KwonDae commented on data/build.gradle.kts
> +dependencies {
@hoyahozz @jihee-dev 
앗 죄송해요 글라이드가 아니라 레트로핏을 말하고 싶었어요 ㅋㅋㅋ

코일을 사용할거고 코일은 프레젠테이션 모듈로
통신관련 라이브러리는 데이터모듈로!

2022-05-20 10:54 UTC, jihee-dev commented on data/build.gradle.kts
> +dependencies {
ㅋㅋㅋㅋ 조하여

2022-05-20 11:55 UTC, hoyahozz commented on domain/src/main/java/com/yapp/growth/domain/usecase/useCase.kt
> +class useCase {
c760cca512c4a9fdb8601f72a9088ad53662153c
_😵 정신이 나갔었나봐~ 그때~_

2022-05-20 12:34 UTC, hoyahozz commented on data/build.gradle.kts
> +dependencies {
105810256fca2d430536a74c29315f5203460cdf
필요한 기초 라이브러리 추가 완료했습니다 :)

2022-05-22 05:07 UTC, jihee-dev approved these changes
LGTM~~

2022-05-22 05:08 UTC, KwonDae approved these changes

2022-05-22 05:09 UTC, KwonDae commented
LGTM~

2022-05-22 05:09 UTC, KwonDae approved these changes
Good 👍

2022-05-22 05:20 UTC, merged