[ISSUE-10] Debug 키스토어 공유
YAPP-Github/20th-Android-Team-1-FE pull request #33
Opened 2022-06-01 17:16 UTC by jihee-dev

## ISSUE
- resolved #10 
<br>

## 작업 내용
- Debug 키스토어를 공유합니다

<br>

## 실행 화면

| Screen Shot | Screen Shot |
| ----------- | ----------- |
|             |             |

<br>

## Check List
- [ ] PR 제목은 `[TICKET-{N}] PR 제목`으로 작성
- [ ] CI/CD 통과 여부
- [ ] 1명 이상의 Approve 확인 후 Merge
- [ ] 관련 이슈 연결

2022-06-01 18:05 UTC, hoyahozz commented on app/build.gradle.kts
>          release {
요기 빌드 타입에 디버그 타입은 추가 안해도 되나용?

2022-06-03 05:58 UTC, jihee-dev commented on app/build.gradle.kts
>          release {
빌드 > 디버그 타입에 어떤 게 추가되어야 할까여?

2022-06-03 09:25 UTC, KwonDae requested changes
고생하셨습니다 :) 👍

2022-06-03 09:25 UTC, KwonDae commented on app/build.gradle.kts
>          release {
debug 랑 release만 들어가면 될 것 같아요
혹시 몰라서 debug 타입과 release 타입을 나누고자 이슈를 생성했는데 어떠신가요? 
ex) 프로가드

2022-06-03 10:19 UTC, jihee-dev commented on app/build.gradle.kts
>          release {
이슈 어디에 추가해 주셨나여? 지금 PR에 해당 내용 포함해서 올려볼게요

2022-06-03 10:32 UTC, KwonDae commented on app/build.gradle.kts
>          release {
생성했습니다~

2022-06-03 10:33 UTC, jihee-dev commented on app/build.gradle.kts
>          release {
넵 👍

2022-06-03 11:38 UTC, KwonDae approved these changes
LGTM 👍

2022-06-03 15:19 UTC, merged