[ISSUE-38] 디자인 베이스 추가 및 적용
YAPP-Github/20th-Android-Team-1-FE pull request #39
Opened 2022-06-10 09:21 UTC by hoyahozz

## ISSUE
- resolved #38

<br>

## 작업 내용
- **로고** 추가
- 현재까지 디자인된 **아이콘** 추가
- 기본 **색상** 추가
- 기본 **폰트** 추가
- **참고사항** : **디자이너분께 색상, 폰트 관련 자세한 정보를 전달받은 후 수정이 필요할 것**으로 보입니다.

<br>

## 실행 화면

| Screen Shot | Screen Shot |
| ----------- | ----------- |
|             |             |

<br>

## Check List
- [x] PR 제목은 `[ISSUE-{N}] PR 제목`으로 작성
- [ ] CI/CD 통과 여부
- [ ] 1명 이상의 Approve 확인 후 Merge
- [x] 관련 이슈 연결

2022-06-10 14:04 UTC, jihee-dev approved these changes
좋아욥

2022-06-10 14:04 UTC, jihee-dev commented on presentation/src/main/java/com/yapp/growth/presentation/theme/Color.kt
> +val Coral       = Color(0XFFFF7F77)
이 색상 이름을 MainPurple, SubYellow, SubCoral 이런 식으로 변경해도 좋을 것 같아요!

2022-06-10 14:04 UTC, jihee-dev commented on presentation/src/main/java/com/yapp/growth/presentation/theme/Type.kt
>  val Typography = Typography(
`PlanzTypograpy` or `GrowthTypograpy`?? 이런 식으로 네이밍을 변경해도 좋지 않을까 싶습니다!

2022-06-10 14:18 UTC, jihee-dev requested changes
로고 파일을 뒤늦게 확인해서 해당 부분만 맞춰서 수정해 주시면 좋을 것 같습니다

+ 추가로 연보라색 테두리가 있는 좌우 화살표..? 요 버튼 아이콘도 리소스 추가해 주시면 감사하겠습니다!!

2022-06-10 14:18 UTC, jihee-dev commented on presentation/src/main/res/drawable/ic_logo.xml
> +</vector>
이걸 지금 확인했네요
혹시 이 로고는 무엇을 위한 리소스인가요? 앱 아이콘이라면 배경까지 같이 추가되어야 할 것 같고,
제가 확인하기로는 로고가 쓰이는 곳이 앱 아이콘 제외하고 스플래시 화면밖에 없는데 스플래시 화면에서 쓰이는 로고는 해당 로고와 크기가 다른 것 같아서요!

2022-06-11 08:10 UTC, hoyahozz commented on presentation/src/main/res/drawable/ic_logo.xml
> +</vector>
처음에 스플래시 로고로 사용하려고 했었는데, 확실히 크기가 안맞네요.. 수정해서 커밋하고, 앱 아이콘도 따로 추가해두도록 하겠습니다 :)

2022-06-11 09:36 UTC, hoyahozz commented on presentation/src/main/java/com/yapp/growth/presentation/theme/Type.kt
>  val Typography = Typography(
좋은 것 같습니당!

1a4e987baed1ed07bd3ab80de31d1d99e968d067

네이밍 수정 완료했습니다 :)

2022-06-11 09:36 UTC, hoyahozz commented on presentation/src/main/res/drawable/ic_logo.xml
> +</vector>
dd911e382ad93552bd4b69a5b219ca5f4a790122

기존 로고 삭제 후 스플래시 로고 추가 완료하였습니다!

2022-06-11 09:38 UTC, hoyahozz commented on presentation/src/main/res/drawable/ic_logo.xml
> +</vector>
<img width="84" alt="image" src="https://user-images.githubusercontent.com/85336456/173182434-f01a296b-8c74-48c8-b042-ced426a76eec.png">

앱 아이콘도 함께 추가 후 적용하려고 했는데, 아이콘이 묘하게 중앙 정렬이 안되는게 킹받는데 이거 디자이너분께 요청해야 하는 사항인가요?

2022-06-11 10:56 UTC, jihee-dev commented on presentation/src/main/res/drawable/ic_logo.xml
> +</vector>
요거 디자이너 분께 보여드리고 말씀드리는 게 좋을 것 같아요 ㅋㅋㅋㅋ

2022-06-11 10:57 UTC, jihee-dev approved these changes
고생하셨습니다!!

2022-06-11 13:05 UTC, merged