[ISSUE-43] 홈 화면 UI 구현
YAPP-Github/20th-Android-Team-1-FE pull request #73
Opened 2022-06-29 12:00 UTC by hoyahozz

## ISSUE
- resolved #43 

<br>

## 작업 내용
- 홈 화면의 UI 구현
- 공통 컴포넌트로 사용할 캘린더 UI 구현
- 바텀 네비게이션이 화면을 가리는 오류 해결
- [MaterialCalendarView](https://github.com/prolificinteractive/material-calendarview) 의존성 추가
- `Compose ConstraintLayout` 의존성 추가

<br>

## 실행 화면

| Screen Shot | Screen Shot |
| ----------- | ----------- |
|  ![Screenshot_1656503730](https://user-images.githubusercontent.com/85336456/176430572-c43dc94d-f726-45d2-98ff-29cfd2b1ac1f.png)        |     |   ![Home](https://user-images.githubusercontent.com/85336456/176431085-78875c71-4d33-45c0-8ebe-5930115ee1a1.gif)     |

<br>

## Check List
- [x] PR 제목은 `[ISSUE-{N}] PR 제목`으로 작성
- [ ] CI/CD 통과 여부
- [ ] 1명 이상의 Approve 확인 후 Merge
- [x] 관련 이슈 연결

2022-06-29 13:18 UTC, jihee-dev requested changes
변경사항이 엄청나네요 ㅠㅠ 고생하셨습니다!! 👍

전반적으로 컴포저블 함수들의 이름이 조금 더 명확하게 무슨 화면을 그리고 있는지 설명할 수 있는 이름이었으면 좋겠습니다!
그리고 따로 하나씩 분리될 수 있는 화면들은 함수를 분리해서 작성하면 조금 더 가독성이 좋을 것 같아요!

2022-06-29 13:18 UTC, jihee-dev commented on presentation/src/main/java/com/yapp/growth/presentation/ui/main/home/HomeScreen.kt
> +fun HomeIsNotLoginBox() {
위의 코멘트와 동일합니다

2022-06-29 13:18 UTC, jihee-dev commented on presentation/src/main/java/com/yapp/growth/presentation/ui/main/home/HomeScreen.kt
> +fun ItemTextPlan(content: String) {
`ItemTodayPlan`과 어떻게 다른 화면인가요?

2022-06-29 13:28 UTC, jihee-dev requested changes
추가로 지금 크기들이 피그마에 소수점 단위로 보이는 건 알지만.. 유도리있게 되도록이면 4의 배수 혹은 못해도 짝수로는 맞춰주시면 더 좋을 것 같아요!

2022-06-29 13:28 UTC, jihee-dev commented on presentation/src/main/java/com/yapp/growth/presentation/ui/main/home/HomeScreen.kt
> +    ConstraintLayout(
이거 그냥 Row로 해도 좋을 것 같은데 ConstraintLayout으로 사용한 이유가 있을까요?

2022-06-29 13:33 UTC, hoyahozz commented on presentation/src/main/java/com/yapp/growth/presentation/ui/main/home/HomeScreen.kt
> +    ConstraintLayout(
디자인에서는 텍스트가 그림의 중앙을 기준으로 수평을 유지하도록 구성되어 있는데, `Row`로 구성해보니 텍스트가 묘하게 중앙정렬이 안돼서 우선 `ConstraintLayout`으로 설정했습니다ㅠ

한번 더 `Row`로 시도해보겠습니다~!

2022-06-29 13:34 UTC, hoyahozz commented on presentation/src/main/java/com/yapp/growth/presentation/ui/main/home/HomeScreen.kt
> +fun HomeTopBox(loginState: HomeContract.LoginState) {
크게 기준을 앱바 - 상단 박스 - 하단 박스 요렇게 세 단계로 분류를 잡아서 분리했습니다..!
홈 화면 외에서 활용되지 않을 것 같아서 기준을 이런식으로 잡았어여..!

2022-06-29 13:35 UTC, jihee-dev commented on presentation/src/main/java/com/yapp/growth/presentation/ui/main/home/HomeScreen.kt
> +    ConstraintLayout(
아하 이거 row modifier에 `verticalAlignment = Alignment.CenterVertically` 적용해 보시면 해결할 수 있을 것 같아요!

2022-06-29 13:36 UTC, hoyahozz commented on presentation/src/main/java/com/yapp/growth/presentation/ui/main/home/HomeScreen.kt
> +private fun HomeAppBar(
움 제가 네이밍 기준을 완전히 잘못잡고 있었던 것 같아여 ㅠ
XML에서는 보통 홈 액티비티라고 하면 ID에 `Home` 을 붙이면서 시작해서, 컴포즈에도 그런식으로 적용을 했던 것 같아여ㅠ..

2022-06-29 13:45 UTC, hoyahozz commented on presentation/src/main/java/com/yapp/growth/presentation/ui/main/home/HomeScreen.kt
> +    ConstraintLayout(
오 그거 넣고 했었는데 뭐라해야되지... 암튼 똑같이 텍스트가 묘하게 아래로 내려가있어서..............ㅎㅎ;;;;;;;;;;;;;;;;

2022-06-29 13:52 UTC, jihee-dev commented on presentation/src/main/java/com/yapp/growth/presentation/ui/main/home/HomeScreen.kt
> +fun HomeTopBox(loginState: HomeContract.LoginState) {
상단 박스가 약속 박스고 하단 박스가 캘린더 박스인가요?

2022-06-29 14:19 UTC, jihee-dev commented on presentation/src/main/java/com/yapp/growth/presentation/ui/main/home/HomeScreen.kt
> +    ConstraintLayout(
넵 좋아용

2022-06-29 15:04 UTC, jihee-dev commented
다른 화면 구현하다가 발견해서 아까 이해하지 못한 코드 이해하게 됐는데,
그 PlanText? 이게 그 월별 약속 리스트의 아이템인 것 같더라고요!
네이밍 추천하자면 `TodayPlans` - `TodayPlanItem` / `MonthPlans` - `MonthPlanItem` 어떠신가요
변경했으면 좋겠다고 리뷰만 드리고 더 좋은 네이밍을 생각해내지 못해서 찜찜했는데 생각난 김에 의견 남깁니당

2022-06-30 01:07 UTC, hoyahozz commented on presentation/src/main/java/com/yapp/growth/presentation/ui/main/home/CalendarDecorator.kt
> +            val calendar = day!!.calendar
`addDecorator`를 할 때 `null`이면 데코레이팅 자체를 해주지 않는 로직이 있어서, `CalendarDay?`에서 `?`를 빼줘도 될 것 같네요! 지적해주셔서 감사합니다 :)

2022-06-30 07:48 UTC, hoyahozz commented on presentation/src/main/java/com/yapp/growth/presentation/ui/main/home/CalendarDecorator.kt
> +        private val boldSpan: StyleSpan = StyleSpan(Typeface.BOLD)
f7970097fa915e397b8a31d8d8976fd548852661
🫠🫠🫠🫠🫠

2022-06-30 07:48 UTC, hoyahozz commented on presentation/src/main/java/com/yapp/growth/presentation/ui/main/home/CalendarDecorator.kt
> +            val calendar = day!!.calendar
f7970097fa915e397b8a31d8d8976fd548852661
🫠🫠🫠🫠🫠

2022-06-30 07:48 UTC, hoyahozz commented on presentation/src/main/java/com/yapp/growth/presentation/ui/main/home/CalendarDecorator.kt
> +            val calendar = day!!.calendar
f7970097fa915e397b8a31d8d8976fd548852661
🫠🫠🫠🫠🫠

2022-06-30 07:48 UTC, hoyahozz commented on presentation/src/main/java/com/yapp/growth/presentation/ui/main/home/CalendarDecorator.kt
> +            return day?.equals(date)!!
f7970097fa915e397b8a31d8d8976fd548852661
🫠🫠🫠🫠🫠

2022-06-30 07:49 UTC, hoyahozz commented on presentation/src/main/java/com/yapp/growth/presentation/ui/main/home/HomeScreen.kt
> +                        text = "오늘의 약속",
ffb80b0164061e58fb1a1c4a480f216bcce29f5b
🫠🫠🫠🫠🫠

2022-06-30 07:50 UTC, hoyahozz commented on presentation/src/main/java/com/yapp/growth/presentation/ui/main/home/HomeScreen.kt
> +fun HomeIsLoginBox() {
34e1dd69013888df0b84425b3490dddb716c224a
🫠🫠🫠🫠🫠

2022-06-30 07:50 UTC, hoyahozz commented on presentation/src/main/java/com/yapp/growth/presentation/ui/main/home/HomeScreen.kt
> +fun HomeTopBox(loginState: HomeContract.LoginState) {
34e1dd69013888df0b84425b3490dddb716c224a
🫠🫠🫠🫠🫠

2022-06-30 07:50 UTC, hoyahozz commented on presentation/src/main/java/com/yapp/growth/presentation/ui/main/home/HomeScreen.kt
> +fun HomeIsNotLoginBox() {
34e1dd69013888df0b84425b3490dddb716c224a
🫠🫠🫠🫠🫠

2022-06-30 07:50 UTC, hoyahozz commented on presentation/src/main/java/com/yapp/growth/presentation/ui/main/home/HomeScreen.kt
> +fun ItemTextPlan(content: String) {
34e1dd69013888df0b84425b3490dddb716c224a
🫠🫠🫠🫠🫠

2022-06-30 07:51 UTC, hoyahozz commented on presentation/src/main/res/drawable/ic_calendar_arrow_left.xml
> +</vector>
84c45477ed38f2b03516e7fdf79b44bd61af5b03
🫠🫠🫠🫠🫠

2022-07-02 06:20 UTC, jihee-dev commented on presentation/src/main/java/com/yapp/growth/presentation/ui/main/home/CalendarDecorator.kt
> +            val calendar = day!!.calendar
qqervtklewjk

2022-07-02 06:26 UTC, KwonDae commented on presentation/src/main/java/com/yapp/growth/presentation/ui/main/home/CalendarDecorator.kt
> +                view?.addSpan(boldSpan)
test comment

2022-07-02 06:27 UTC, KwonDae commented on presentation/src/main/java/com/yapp/growth/presentation/ui/main/home/HomeViewModel.kt
> +    // TODO : 로그인 여부 체크(정호)
```suggestion
    // TODO : 로그인 여부 체크(정호)
    test
```

test 입니당

2022-07-03 18:40 UTC, jihee-dev commented
캘린더 밑 Padding이랑 그림자 추가하시고 머지 부탁드려용

2022-07-03 18:40 UTC, jihee-dev approved these changes

2022-07-05 08:44 UTC, merged