[ISSUE-55] 약속 생성 STEP 4 시간대 선택 UI
YAPP-Github/20th-Android-Team-1-FE pull request #82
Opened 2022-07-07 18:15 UTC by jihee-dev

## ISSUE
- resolved #55 

<br>

## 작업 내용
- 플랜즈 약속 생성 타이틀 바 타입 추가
  - description 타입, other contents 추가 타입
- 약속 생성 STEP 3 UI 구현(캘린더 제외)
- 플랜즈 스낵바 컴포넌트 추가
- 약속 생성 STEP 4(시간대 선택) UI 구현
- 약속 생성 STEP 3, 4 네비게이션 연결

<br>

## 실행 화면

| Screen Shot | Screen Shot |
| ----------- | ----------- |
| <img width="512" alt="스크린샷 2022-07-08 오전 3 11 47" src="https://user-images.githubusercontent.com/42907876/177841067-490c783e-02d1-4c52-ac9b-4e807cb3a7b8.png"> | <img width="512" alt="스크린샷 2022-07-08 오전 3 12 07" src="https://user-images.githubusercontent.com/42907876/177841126-04e79d85-1428-482b-bcbc-d55e728709f4.png"> |
| <img width="512" alt="스크린샷 2022-07-08 오전 3 12 38" src="https://user-images.githubusercontent.com/42907876/177841207-e547741a-3e0f-41ef-8a8f-70b5760375e1.png"> | <img width="512" alt="스크린샷 2022-07-08 오전 3 13 10" src="https://user-images.githubusercontent.com/42907876/177841287-6a718298-3f23-4855-ade1-f4cf12209ea0.png"> |
| <img width="512" alt="스크린샷 2022-07-08 오전 3 14 04" src="https://user-images.githubusercontent.com/42907876/177841430-d18c90bc-94e0-4b65-8a9d-9471999ce68d.png"> |  |

<br>

## Check List
- [x] PR 제목은 `[ISSUE-{N}] PR 제목`으로 작성
- [x] CI/CD 통과 여부
- [x] 1명 이상의 Approve 확인 후 Merge
- [x] 관련 이슈 연결

2022-07-08 06:01 UTC, hoyahozz approved these changes
코드 모두 꼼꼼하게 보았는데, 어려운 로직임에도 굉장히 가독성 좋게 코드 짜신 것 같아요~~!
너무너무 고생하셨습니다 :)

2022-07-08 14:29 UTC, jihee-dev commented on presentation/src/main/java/com/yapp/growth/presentation/model/TimeType.kt
> +enum class TimeType(val timeStringResId: Int) {
ㅌㅋㅋㅋㅋㅋ 정신 나가는 줄 알았어요

2022-07-09 07:08 UTC, KwonDae requested changes
state hoisting 과 컴포넌트화에 신경을 쓰신거 같아서 고생많으셨다는 생각이 들었습니다 ㅎㅎ
코멘트 몇개 드린것만 확인 부탁드릴게요!
👍

2022-07-09 07:08 UTC, KwonDae commented on presentation/src/main/java/com/yapp/growth/presentation/ui/main/create/timerange/TimeRangeViewModel.kt
> +    }
```suggestion
private fun checkRangeError(startHour: Int?, endHour: Int?) {
    if (startHour == null || endHour == null) {
        showErrorState(isError = true)
        return
    } else if (startHour >= endHour) {
        showErrorState(isError = true, showSnackBar = true)
        return
    }
    
    showErrorState(isError = false)
}
```

이 부분 임시로 이렇게 하신건가요? 아니라면 이런식으로 코드를 리펙토링 할 수 있을거 같아요!

2022-07-11 14:35 UTC, KwonDae commented on presentation/src/main/java/com/yapp/growth/presentation/ui/main/create/timerange/TimeRangeViewModel.kt
> +    }
suggest 방식에서도 start 와 end 모두 null 체크를 해주어서 else if 로 가면 둘다 nullable 하지 않게 캐스팅 되어서 비교가 가능한거 같던데 저렇게하면 에러가 나나요?

2022-07-11 14:42 UTC, KwonDae commented on presentation/src/main/java/com/yapp/growth/presentation/ui/main/create/timerange/TimeRangeViewModel.kt
> +    }
조아용 스마트 캐스팅 되어서 비교가 가능하기에 참고해서 구현하시면 될 것 같슴다!

2022-07-11 15:38 UTC, jihee-dev commented on presentation/src/main/java/com/yapp/growth/presentation/ui/main/create/timerange/TimeRangeViewModel.kt
> +    }
오 위에 답글을 못 봤네요 ㅠㅠ
처음에 저런 방식으로 해뒀는데 스마트 캐스팅이 안 먹혀서 자꾸 빌드에 실패하더라고요
다시 해 보니 되는 걸 보니까 아마 버그였던가,, 그랬던 것 같은데.. (클린 후에 재빌드하면 괜찮았을지도.. 모른다는 생각이 드네용...)
저는 또 함수 파라미터로 전달받은 값은 스마트 캐스팅이 안 되게 되어 있다거나 그런 건 줄 알았어요 ㅠㅠㅋㅋㅋ쿠ㅜㅜㅜ 😅

2022-07-11 22:28 UTC, KwonDae approved these changes
조아용 머지하시고 브랜치 삭제해주시면 될 것 같아요~
고생하셨습니다~ 👍

2022-07-12 14:08 UTC, merged