[ISSUE-44, 63, 86] 시간표 컴포넌트 구현 & 약속응답 화면 UI 구현
YAPP-Github/20th-Android-Team-1-FE pull request #88
Opened 2022-07-12 16:27 UTC by KwonDae

## ISSUE
- resolved #44 
- resolved #63 
- resolved #86 

<br>

## 작업 내용
- 시간표 UI 컴포넌트  구현
- 약속관리 - 약속응답 화면 구현
  - 다수의 시간을 선택할 수 있으며, 버튼 개수에 따른 state 를 처리했습니다.
- 약속관리 - 약속확정 화면 구현
  - 버튼 하나만 감지하고, 바텀시트를 함께 적용했습니다.

<br>

## 실행 화면

| Screen Shot | Screen Shot |
| ----------- | ----------- |
|![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/33443660/178544298-78575079-176d-423c-8d45-0741038b0aad.gif) |![ezgif com-gif-maker (4)](https://user-images.githubusercontent.com/33443660/178544348-38e588a4-6733-4f13-a099-3332c58c4e26.gif)|

<br>

## Check List
- [ ] PR 제목은 `[ISSUE-{N}] PR 제목`으로 작성
- [ ] CI/CD 통과 여부
- [ ] 1명 이상의 Approve 확인 후 Merge
- [ ] 관련 이슈 연결

2022-07-12 16:33 UTC, KwonDae commented
@jihee-dev @hoyahozz 
양이 조금 많습니다.. 그래서 약속응답(RespondPlan) 쪽은 지난 피알에서 네이밍 변경이 주로 변경되었고,
약속확정(ConfirmPlan) 이 새롭게 커밋되어 피알을 올렸습니다.

약속확정 쪽으로 봐주시면 좋을 것 같아요!

2022-07-14 15:17 UTC, jihee-dev commented
고냥 사소한 질문인데
저희 디자인상에서는 유저가 선택한 칸의 색에 알파 값이 살짝 들어가서 배경으로 다른 친구들의 시간이 보이면서 자신의 시간이 같이 보이는 게 장점이라고 생각했거든요..!
근데 스크린샷에는 그 테두리 색이 전체 칸 색으로 들어간 것 같아서 그렇게 협의된 것인지 궁금합니당

2022-07-14 15:30 UTC, KwonDae commented
> 고냥 사소한 질문인데
> 저희 디자인상에서는 유저가 선택한 칸의 색에 알파 값이 살짝 들어가서 배경으로 다른 친구들의 시간이 보이면서 자신의 시간이 같이 보이는 게 장점이라고 생각했거든요..!
> 근데 스크린샷에는 그 테두리 색이 전체 칸 색으로 들어간 것 같아서 그렇게 협의된 것인지 궁금합니당

아 그러네요 디테일하게 확인을 못했던거 같습니다
이부분 수정해볼게요!

2022-07-14 15:48 UTC, jihee-dev requested changes
코드양이 어마어마 하네요..! 정말 고생 많으셨습니다 👍👍
일단 눈에 보이는 것 먼저 코멘트 남겨드려요!
화면에 보여야 할 데이터(상태)들이 ViewModel의 State로 묶여서 관리되어야 하는데 개별적으로 되어 있고,
viewState가 전부 이용되지 않고 있어서 이 부분 수정이 필요할 것 같습니다..! ㅜㅜ

2022-07-14 15:48 UTC, jihee-dev commented on data/src/main/java/com/yapp/growth/data/mapper/ResponseToModelMapper.kt
> +fun mapUserDto(input: UserResponse): TestingUser {
저희 매퍼를 따로 파일로 분리해서 관리하나용?
파일이 많아지는 것 같아서 모델의 companion object로 같이 둬도 괜찮지 않을까 싶습니다!

2022-07-14 15:48 UTC, jihee-dev commented on presentation/src/main/java/com/yapp/growth/presentation/component/PlanzButtons.kt
> +fun PlanzBottomBasicButton(
`PlanzBasicBottomButton` 어떠신가요

2022-07-14 15:48 UTC, jihee-dev commented on presentation/src/main/java/com/yapp/growth/presentation/component/PlanzTimeTable.kt
> +                    } ?:  0x00000000
`0x00000000` -> `Color.Black`
이렇게 변경하면 가독성이 더 좋을 것 같아요!

2022-07-14 15:48 UTC, jihee-dev commented on presentation/src/main/java/com/yapp/growth/presentation/component/PlanzTimeTable.kt
> +                    } ?:  0x00000000
위의 코멘트와 동일합니다!
`Color.Black`

2022-07-16 01:31 UTC, KwonDae commented on presentation/src/main/java/com/yapp/growth/presentation/component/PlanzButtons.kt
> +fun PlanzBottomBasicButton(
[6af5ef8](https://github.com/YAPP-Github/20th-Android-Team-1-FE/pull/88/commits/6af5ef8cd3db8208a6c8174fd1bb06f64b3d98cc)
수정했습니다!

2022-07-16 01:46 UTC, KwonDae commented on presentation/src/main/java/com/yapp/growth/presentation/component/PlanzTimeTable.kt
> +                    } ?:  0x00000000
아 이게 밑에 
`.background(if (upperTableClicked) SubCoral else Color(upperTableColor)),`
에서 Color 안에 들어갈 숫자가 필요해서 저렇게 했었는데 더 나은 방향이 있을까요? ㅠㅠ

2022-07-16 01:47 UTC, KwonDae commented on presentation/src/main/java/com/yapp/growth/presentation/ui/main/manage/confirm/ConfirmPlanContract.kt
> +        val state: Boolean = false
아 여기서도 UiState 를 사용하지 않고 있습니다..
이거 오늘 같이 얘기해보시죠

2022-07-16 01:48 UTC, KwonDae commented on presentation/src/main/java/com/yapp/growth/presentation/ui/login/LoginScreen.kt
> +fun  LoginScreen(
[5f6d2f5](https://github.com/YAPP-Github/20th-Android-Team-1-FE/pull/88/commits/5f6d2f5756a09304c6d6ad5d8b80c6e66308a6a6)
수정했습니다~

2022-07-16 01:52 UTC, KwonDae commented on data/src/main/java/com/yapp/growth/data/mapper/ResponseToModelMapper.kt
> +fun mapUserDto(input: UserResponse): TestingUser {
매퍼는 해당 Response 에 대해 화면에서 데이터 정제가 필요한 경우 xxResponseMapper 안에서 데이터 정제 로직을 모아두는게 효율적이라고 생각했습니다. 정제해야 할 Response 가 많아진다면 이걸 companion object 로 처리해놓았을 때 메모리에 모두 올라가 있을텐데 메모리 관리상 좋지 않을것 같습니다. 이것도 오늘 얘기 해보시죠!

2022-07-16 15:47 UTC, hoyahozz approved these changes
고생 많으셨어요!!! 👍👍👍👍👍

2022-07-17 02:14 UTC, merged